apiVersion: v1
kind: Service
metadata:
 name: postgres-service-pod
 labels:
  name: postgres-service
  app: vote-demo-app
spec:
 type: ClusterIP
 ports:
  - targetPort: 5432 
    port: 5432 
 selector:
  name: postgres-db
  app: demo-voting-app
