apiVersion: v1
kind: Pod
metadata: 
 name: postgresdb-pod
 labels:
  name: postgres-db
  app: demo-voting-app
spec:
 containers:
  - name: postgresdbc1
    image: postgres:15-alpine
    env:
     - name: POSTGRES_USER
       value: postgres
     - name: POSTGRES_PASSWORD
       value: postgres
    ports:
     - containerPort: 5432
