apiVersion: v1
kind: Service
metadata:
 name: redis-service-pod
 labels:
  name: redis-service
  app: vote-demo-app
spec:
 type: ClusterIP
 ports:
  - targetPort: 6379
    port: 6379
 selector:
  name: redis-app
  app: demo-voting-app
