apiVersion: v1
kind: Service
metadata:
 name: result-service-pod
 labels:
  name: vote-service
  app: demo-voting-app
spec:
 type: LoadBalancer
 ports:
  - targetPort: 80
    port: 80
 selector:
  name: result-app
  app: demo-voting-app
