apiVersion: v1
kind: Pod
metadata:
 name: result-pod
 labels:
  name: result-app
  app: demo-voting-app
spec:
 containers:
  - name: resultc1
    image: docker/example-voting-app-result
    ports:
     - containerPort: 80
