apiVersion: v1
kind: Service
metadata:
 name: vote-service-pod
 labels:
  type: voting-cast
  author: Swetha
spec:
 type: LoadBalancer
 ports:
  - targetPort: 80
    port: 80
 selector:
  type: voting-cast
  author: Swetha
