apiVersion: v1
kind: Pod
metadata:
 name: voting-pod
 labels:
  type: voting-cast
  author: Swetha
spec:
 containers:
  - name: votingc1
    image: dockersamples/examplevotingapp_vote
    ports:
     - containerPort: 80
