apiVersion: v1 
kind: Service
metadata: 
  name: vote-service
  labels:
    name: vote-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodeport: 30005
  selector:
    name: voting-pod
    app: demo-voting-app